services:
    api:
        build: ./
        volumes:
            - ./data:/app/data
        environment:
            - PYTHONUNBUFFERED=1
        network_mode: host # Only works on Linux
        dns:
            - 8.8.8.8
            - 8.8.4.4
