services:
    api:
        build: ./
        volumes:
            - ./data:/app/data
        environment:
            - PYTHONUNBUFFERED=1
        dns:
            - 8.8.8.8
            - 8.8.4.4
        ports:
            - "5001:5001"
        env_file:
            - .env
