services:
    api:
        build: ./
        volumes:
            - ./data:/app/data
        environment:
            - PYTHONUNBUFFERED=1
        dns:
            - 8.8.8.8
            - 8.8.4.4
        ports:
            - "5050:5050"
        env_file:
            - .env
